baseURL = 'https://pustaka.learntera.org/'
languageCode = 'en-us'
title = 'Learntera Library'
theme = 'hugo-theme-stack'

[params]
    favicon = "/favicon.ico"
    [params.sidebar]
        subtitle = "tempat dimana kita belajar, mempraktekkan, dan mengamalkan ilmu"
    [params.sidebar.avatar]
        enabled = true
        src = "/learntera-library.png"